### ISSUE TITLE
InterruptedException happened even when succeeded 

### ISSUE THREAD

**Issue by bfeng** [knram06/mpich2-yarn#6]
The following exception is observed with Cgroups enabled even when it finished successfully.

```
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:287)
```

**Comment by bfeng** [comment]
Fixed in dbe8d979b27a4b7cf1f886ad6e6f8995c1e82ffe
